/// Syllable counting service for haiku composition.
///
/// Uses a dictionary-based approach with vowel-counting fallback
/// for unknown words. Handles contractions and edge cases.
library;

/// Count the number of syllables in a word.
///
/// Uses dictionary lookup first, then falls back to vowel counting.
int countSyllablesInWord(String word) {
  if (word.isEmpty) return 0;

  final cleaned = word.toLowerCase().replaceAll(RegExp(r"[^a-z']"), '');
  if (cleaned.isEmpty) return 0;

  // Check dictionary first
  final dictCount = _dictionary[cleaned];
  if (dictCount != null) return dictCount;

  // Handle contractions
  final contractionCount = _countContraction(cleaned);
  if (contractionCount != null) return contractionCount;

  // Fall back to vowel counting algorithm
  return _countByVowels(cleaned);
}

/// Count syllables in a line of text.
int countSyllablesInLine(String line) {
  if (line.trim().isEmpty) return 0;

  final words = line.split(RegExp(r'\s+'));
  int total = 0;
  for (final word in words) {
    total += countSyllablesInWord(word);
  }
  return total;
}

/// Count syllables in each line of a haiku.
///
/// Returns a list of syllable counts, one per line.
List<int> countHaikuSyllables(String text) {
  final lines = text.split('\n');
  return lines.map(countSyllablesInLine).toList();
}

/// Check if the haiku follows the 5-7-5 pattern.
bool isValidHaikuStructure(String text) {
  final counts = countHaikuSyllables(text);
  if (counts.length != 3) return false;
  return counts[0] == 5 && counts[1] == 7 && counts[2] == 5;
}

/// Handle common contractions.
int? _countContraction(String word) {
  // Common contraction patterns
  const contractions = <String, int>{
    // 1 syllable contractions
    "i'm": 1,
    "you're": 1,
    "we're": 1,
    "they're": 1,
    "he's": 1,
    "she's": 1,
    "it's": 1,
    "that's": 1,
    "what's": 1,
    "who's": 1,
    "there's": 1,
    "here's": 1,
    "where's": 1,
    "let's": 1,
    "i've": 1,
    "you've": 1,
    "we've": 1,
    "they've": 1,
    "i'll": 1,
    "you'll": 1,
    "he'll": 1,
    "she'll": 1,
    "it'll": 2,
    "we'll": 1,
    "they'll": 1,
    "i'd": 1,
    "you'd": 1,
    "he'd": 1,
    "she'd": 1,
    "we'd": 1,
    "they'd": 1,
    "isn't": 2,
    "aren't": 1,
    "wasn't": 2,
    "weren't": 1,
    "hasn't": 2,
    "haven't": 2,
    "hadn't": 2,
    "doesn't": 2,
    "don't": 1,
    "didn't": 2,
    "won't": 1,
    "wouldn't": 2,
    "can't": 1,
    "couldn't": 2,
    "shouldn't": 2,
    "mightn't": 2,
    "mustn't": 2,
    "needn't": 2,
    // 2 syllable contractions
    "cannot": 2,
    "gonna": 2,
    "wanna": 2,
    "gotta": 2,
    "kinda": 2,
    "sorta": 2,
    "coulda": 2,
    "woulda": 2,
    "shoulda": 2,
    "oughta": 2,
    "hafta": 2,
    "useta": 3,
    "supposta": 3,
    // Possessive contractions
    "y'all": 1,
    "ma'am": 1,
    "o'clock": 2,
    "ne'er": 1,
    "e'er": 1,
    "o'er": 1,
  };

  return contractions[word];
}

/// Count syllables using vowel patterns.
///
/// This is the fallback algorithm when a word isn't in the dictionary.
int _countByVowels(String word) {
  if (word.isEmpty) return 0;

  // Vowel pattern
  final vowels = RegExp(r'[aeiouy]+', caseSensitive: false);
  final matches = vowels.allMatches(word);
  int count = matches.length;

  // Adjust for silent 'e' at end
  if (word.endsWith('e') && !word.endsWith('le')) {
    // Check if 'e' follows a consonant (silent e)
    if (word.length > 1) {
      final beforeE = word[word.length - 2];
      if (!'aeiouy'.contains(beforeE)) {
        count = count > 1 ? count - 1 : count;
      }
    }
  }

  // Words ending in 'le' after consonant add a syllable
  if (word.length > 2 && word.endsWith('le')) {
    final beforeLe = word[word.length - 3];
    if (!'aeiouy'.contains(beforeLe)) {
      // 'le' is its own syllable - already counted by vowel match
    }
  }

  // Adjust for common suffixes that are syllabic
  if (word.endsWith('ed')) {
    final beforeEd = word.length > 2 ? word[word.length - 3] : '';
    // 'ed' is silent after most consonants except t/d
    if (beforeEd == 't' || beforeEd == 'd') {
      // 'ed' is pronounced as separate syllable
      // Already counted
    }
  }

  // Handle 'tion', 'sion' as single syllable (already matched as 'io')
  // Handle 'eous', 'ious' patterns
  if (word.contains('eous') || word.contains('ious')) {
    count = count > 1 ? count - 1 : count;
  }

  // Ensure at least 1 syllable for any word
  return count > 0 ? count : 1;
}

/// Dictionary of common words and their syllable counts.
///
/// This subset covers common English words, especially those
/// that might appear in haiku about tea, coffee, and nature.
const _dictionary = <String, int>{
  // Single syllable words
  'a': 1,
  'an': 1,
  'the': 1,
  'and': 1,
  'or': 1,
  'but': 1,
  'for': 1,
  'nor': 1,
  'yet': 1,
  'so': 1,
  'as': 1,
  'at': 1,
  'by': 1,
  'in': 1,
  'of': 1,
  'on': 1,
  'to': 1,
  'up': 1,
  'is': 1,
  'it': 1,
  'be': 1,
  'he': 1,
  'we': 1,
  'me': 1,
  'my': 1,
  'no': 1,
  'do': 1,
  'go': 1,
  'if': 1,
  'am': 1,
  'i': 1,
  'you': 1,
  'your': 1,
  'are': 1,
  'was': 1,
  'were': 1,
  'been': 1,
  'have': 1,
  'has': 1,
  'had': 1,
  'will': 1,
  'would': 1,
  'could': 1,
  'should': 1,
  'may': 1,
  'might': 1,
  'must': 1,
  'can': 1,
  'this': 1,
  'that': 1,
  'these': 1,
  'those': 1,
  'what': 1,
  'which': 1,
  'who': 1,
  'whom': 1,
  'where': 1,
  'when': 1,
  'why': 1,
  'how': 1,
  'all': 1,
  'each': 1,
  'both': 1,
  'few': 1,
  'more': 1,
  'most': 1,
  'some': 1,
  'any': 2,
  'one': 1,
  'two': 1,
  'three': 1,
  'four': 1,
  'five': 1,
  'six': 1,
  'first': 1,
  'last': 1,
  'new': 1,
  'old': 1,
  'good': 1,
  'great': 1,
  'small': 1,
  'large': 1,
  'long': 1,
  'short': 1,
  'high': 1,
  'low': 1,
  'deep': 1,
  'wide': 1,
  'dark': 1,
  'light': 1,
  'bright': 1,
  'warm': 1,
  'cool': 1,
  'cold': 1,
  'hot': 1,
  'soft': 1,
  'hard': 1,
  'slow': 1,
  'fast': 1,
  'still': 1,
  'calm': 1,
  'fresh': 1,
  'sweet': 1,
  'rich': 1,
  'full': 1,
  'pure': 1,
  'true': 1,
  'real': 1,
  'free': 1,
  'own': 1,
  'same': 1,
  'time': 1,
  'day': 1,
  'night': 1,
  'year': 1,
  'week': 1,
  'hour': 1,
  'world': 1,
  'life': 1,
  'home': 1,
  'house': 1,
  'place': 1,
  'room': 1,
  'way': 1,
  'hand': 1,
  'eye': 1,
  'eyes': 1,
  'face': 1,
  'head': 1,
  'heart': 1,
  'mind': 1,
  'soul': 1,
  'name': 1,
  'word': 1,
  'love': 1,
  'peace': 1,
  'hope': 1,
  'dream': 1,
  'dreams': 1,
  'thought': 1,
  'thoughts': 1,
  'breath': 1,
  'rest': 1,
  'sleep': 1,
  'wake': 1,
  'work': 1,
  'play': 1,
  'wait': 1,
  'watch': 1,
  'see': 1,
  'look': 1,
  'feel': 1,
  'hear': 1,
  'know': 1,
  'think': 1,
  'say': 1,
  'tell': 1,
  'ask': 1,
  'give': 1,
  'take': 1,
  'make': 1,
  'find': 1,
  'leave': 1,
  'keep': 1,
  'let': 1,
  'put': 1,
  'get': 1,
  'come': 1,
  'move': 1,
  'turn': 1,
  'stand': 1,
  'sit': 1,
  'rise': 1,
  'fall': 1,
  'flow': 1,
  'grow': 1,
  'change': 1,
  'bring': 1,
  'hold': 1,
  'run': 1,
  'walk': 1,
  'start': 1,
  'end': 1,
  'stop': 1,
  'live': 1,
  'die': 1,
  'try': 1,
  'need': 1,
  'want': 1,
  'use': 1,
  'help': 1,
  'call': 1,
  'read': 1,
  'write': 1,
  'learn': 1,
  'teach': 1,
  'show': 1,
  'point': 1,
  'reach': 1,
  'touch': 1,
  'drink': 1,
  'pour': 1,
  'sip': 1,
  'taste': 1,
  'smell': 1,
  'cup': 1,
  'bowl': 1,
  'pot': 1,
  'steam': 1,
  'tea': 1,
  'leaf': 1,
  'leaves': 1,
  'green': 1,
  'black': 1,
  'white': 1,
  'bloom': 1,
  'grounds': 1,
  'beans': 1,
  'roast': 1,
  'brew': 1,
  'drip': 1,
  'drop': 1,
  'drops': 1,
  'wave': 1,
  'waves': 1,
  'wind': 1,
  'rain': 1,
  'snow': 1,
  'sun': 1,
  'moon': 1,
  'star': 1,
  'stars': 1,
  'sky': 1,
  'cloud': 1,
  'clouds': 1,
  'mist': 1,
  'fog': 1,
  'dew': 1,
  'dawn': 1,
  'dusk': 1,
  'spring': 1,
  'fall': 1,
  'tree': 1,
  'trees': 1,
  'branch': 1,
  'root': 1,
  'roots': 1,
  'seed': 1,
  'seeds': 1,
  'fruit': 1,
  'stone': 1,
  'stones': 1,
  'rock': 1,
  'rocks': 1,
  'earth': 1,
  'ground': 1,
  'hill': 1,
  'hills': 1,
  'lake': 1,
  'pond': 1,
  'stream': 1,
  'path': 1,
  'road': 1,
  'bird': 1,
  'birds': 1,
  'frog': 1,
  'frogs': 1,
  'fish': 1,
  'here': 1,
  'there': 1,
  'now': 1,
  'then': 1,
  'just': 1,
  'still': 1,
  'once': 1,
  'soon': 1,
  'through': 1,
  'while': 1,
  'quite': 1,
  'much': 1,
  'such': 1,
  'well': 1,
  'back': 1,
  'down': 1,
  'out': 1,
  'off': 1,
  'with': 1,
  'from': 1,
  'than': 1,
  'like': 1,
  'each': 1,
  'just': 1,
  'over': 2,
  'only': 2,
  'other': 2,
  'into': 2,
  'also': 2,
  'very': 2,
  'after': 2,
  'before': 2,
  'again': 2,
  'away': 2,
  'about': 2,
  'under': 2,
  'around': 2,
  'between': 2,
  'without': 2,
  'within': 2,
  'along': 2,
  'across': 2,
  'behind': 2,
  'beside': 2,
  'beyond': 2,
  'against': 2,
  'toward': 2,
  'towards': 2,
  'being': 2,
  'having': 2,
  'doing': 2,
  'going': 2,
  'coming': 2,
  'making': 2,
  'taking': 2,
  'giving': 2,
  'saying': 2,
  'seeing': 2,
  'looking': 2,
  'feeling': 2,
  'thinking': 2,
  'knowing': 2,
  'finding': 2,
  'leaving': 2,
  'keeping': 2,
  'moving': 2,
  'turning': 2,
  'standing': 2,
  'sitting': 2,
  'rising': 2,
  'falling': 2,
  'flowing': 2,
  'growing': 2,
  'changing': 2,
  'holding': 2,
  'running': 2,
  'walking': 2,
  'starting': 2,
  'ending': 2,
  'stopping': 2,
  'living': 2,
  'trying': 2,
  'needing': 2,
  'wanting': 2,
  'using': 2,
  'helping': 2,
  'reading': 2,
  'writing': 2,
  'learning': 2,
  'teaching': 2,
  'showing': 2,
  'reaching': 2,
  'touching': 2,
  'drinking': 2,
  'pouring': 2,
  'tasting': 2,
  'smelling': 2,
  'steaming': 2,
  'brewing': 2,
  'dripping': 2,
  'blooming': 2,
  'raining': 2,
  'snowing': 2,
  'shining': 2,
  // Tea and coffee related
  'coffee': 2,
  'water': 2,
  'morning': 2,
  'evening': 2,
  'winter': 2,
  'summer': 2,
  'autumn': 2,
  'season': 2,
  'seasons': 2,
  'flower': 2,
  'flowers': 2,
  'garden': 2,
  'mountain': 2,
  'mountains': 2,
  'river': 2,
  'rivers': 2,
  'ocean': 2,
  'island': 2,
  'forest': 2,
  'valley': 2,
  'meadow': 2,
  'temple': 2,
  'moment': 2,
  'moments': 2,
  'silence': 2,
  'quiet': 2,
  'peaceful': 2,
  'gentle': 2,
  'slowly': 2,
  'softly': 2,
  'lightly': 2,
  'deeply': 2,
  'simply': 2,
  'truly': 2,
  'spirit': 2,
  'nature': 2,
  'beauty': 2,
  'wonder': 2,
  'wisdom': 2,
  'patience': 2,
  'presence': 2,
  'essence': 2,
  'balance': 2,
  'harmony': 3,
  'tranquil': 2,
  'serene': 2,
  'sacred': 2,
  'ancient': 2,
  'simple': 2,
  'humble': 2,
  'mindful': 2,
  'grateful': 2,
  'thankful': 2,
  'joyful': 2,
  'hopeful': 2,
  'careful': 2,
  'graceful': 2,
  'restful': 2,
  'peaceful': 2,
  'heartfelt': 2,
  'soulful': 2,
  'truthful': 2,
  'faithful': 2,
  // Brewing terms
  'aroma': 3,
  'flavor': 2,
  'flavors': 2,
  'bitter': 2,
  'mellow': 2,
  'earthy': 2,
  'floral': 2,
  'herbal': 2,
  'grassy': 2,
  'vegetal': 3,
  'woody': 2,
  'smoky': 2,
  'nutty': 2,
  'fruity': 2,
  'citrus': 2,
  'honey': 2,
  'caramel': 3,
  'chocolate': 3,
  'vanilla': 3,
  'cinnamon': 3,
  'ginger': 2,
  'jasmine': 2,
  'bergamot': 3,
  'chamomile': 3,
  'lavender': 3,
  'peppermint': 3,
  'spearmint': 2,
  'matcha': 2,
  'oolong': 2,
  'puerh': 2,
  'sencha': 2,
  'gyokuro': 3,
  'genmaicha': 4,
  'hojicha': 3,
  'darjeeling': 3,
  'assam': 2,
  'ceylon': 2,
  'yunnan': 2,
  'keemun': 2,
  'lapsang': 2,
  'souchong': 2,
  'espresso': 3,
  'cappuccino': 4,
  'latte': 2,
  'americano': 4,
  'macchiato': 4,
  'mocha': 2,
  'chemex': 2,
  'aeropress': 3,
  'french': 1,
  'press': 1,
  'filter': 2,
  'kettle': 2,
  'teapot': 2,
  'teacup': 2,
  'gaiwan': 2,
  'kyusu': 2,
  'yixing': 2,
  'ceramic': 3,
  'porcelain': 3,
  'bamboo': 2,
  'wooden': 2,
  'ritual': 3,
  'rituals': 3,
  'ceremony': 4,
  'tradition': 3,
  'traditional': 4,
  'meditate': 3,
  'meditation': 4,
  'contemplate': 3,
  'contemplation': 4,
  'appreciate': 4,
  'appreciation': 5,
  'gratitude': 3,
  'serenity': 4,
  'tranquility': 5,
  'mindfulness': 3,
  'awareness': 3,
  'attention': 3,
  'intention': 3,
  'reflection': 3,
  'introspection': 4,
  // Haiku related
  'haiku': 2,
  'poem': 2,
  'poems': 2,
  'poetry': 3,
  'verse': 1,
  'verses': 2,
  'syllable': 3,
  'syllables': 3,
  'beautiful': 3,
  'wonderful': 3,
  'delicate': 3,
  'exquisite': 3,
  'ephemeral': 4,
  'impermanent': 4,
  'impermanence': 4,
  'transient': 3,
  'fleeting': 2,
  'passing': 2,
  'fading': 2,
  'lingering': 3,
  'lasting': 2,
  'eternal': 3,
  'infinite': 3,
  'beginning': 3,
  'becoming': 3,
  'awakening': 4,
  'unfolding': 3,
  'opening': 3,
  'closing': 2,
  'gathering': 3,
  'scattering': 3,
  'wandering': 3,
  'floating': 2,
  'drifting': 2,
  'swirling': 2,
  'spiraling': 3,
  'dancing': 2,
  'singing': 2,
  'whispering': 3,
  'murmuring': 3,
  'rustling': 2,
  'trickling': 2,
  'rippling': 2,
  'shimmering': 3,
  'glistening': 3,
  'sparkling': 2,
  'glowing': 2,
  'radiating': 4,
  'illuminating': 5,
  'enlightening': 4,
  'remembering': 4,
  'forgetting': 3,
  'releasing': 3,
  'embracing': 3,
  'accepting': 3,
  'receiving': 3,
  'breathing': 2,
  'inhaling': 3,
  'exhaling': 3,
  'centering': 3,
  'grounding': 2,
  'connecting': 3,
  'returning': 3,
  'arriving': 3,
  'departing': 3,
  'journeying': 3,
  'traveling': 3,
  'resting': 2,
  'sleeping': 2,
  'waking': 2,
  'dreaming': 2,
  'imagining': 4,
  'creating': 3,
  'expressing': 3,
  'sharing': 2,
  'offering': 3,
  'receiving': 3,
  'honoring': 3,
  'celebrating': 4,
  'cherishing': 3,
  'treasuring': 3,
  'savoring': 3,
  'enjoying': 3,
  'delighting': 3,
  'inspiring': 3,
  'nourishing': 3,
  'sustaining': 3,
  'supporting': 3,
  'comforting': 3,
  'soothing': 2,
  'calming': 2,
  'relaxing': 3,
  'refreshing': 3,
  'renewing': 3,
  'reviving': 3,
  'restoring': 3,
  'healing': 2,
  'cleansing': 2,
  'purifying': 4,
  'clarifying': 4,
  'simplifying': 4,
  // Numbers as words
  'seven': 2,
  'eight': 1,
  'nine': 1,
  'ten': 1,
  'eleven': 3,
  'twelve': 1,
  'thirteen': 2,
  'fourteen': 2,
  'fifteen': 2,
  'sixteen': 2,
  'seventeen': 3,
  'eighteen': 2,
  'nineteen': 2,
  'twenty': 2,
  'thirty': 2,
  'forty': 2,
  'fifty': 2,
  'sixty': 2,
  'seventy': 3,
  'eighty': 2,
  'ninety': 2,
  'hundred': 2,
  'thousand': 2,
  'million': 2,
  // Common verbs in past tense (irregular)
  'went': 1,
  'came': 1,
  'saw': 1,
  'knew': 1,
  'thought': 1,
  'found': 1,
  'told': 1,
  'made': 1,
  'said': 1,
  'took': 1,
  'gave': 1,
  'left': 1,
  'kept': 1,
  'felt': 1,
  'became': 2,
  'began': 2,
  'brought': 1,
  'bought': 1,
  'built': 1,
  'caught': 1,
  'chose': 1,
  'drawn': 1,
  'driven': 2,
  'eaten': 2,
  'fallen': 2,
  'flown': 1,
  'forgotten': 3,
  'forgiven': 3,
  'frozen': 2,
  'given': 2,
  'gone': 1,
  'grown': 1,
  'heard': 1,
  'hidden': 2,
  'held': 1,
  'known': 1,
  'laid': 1,
  'led': 1,
  'lain': 1,
  'lost': 1,
  'meant': 1,
  'met': 1,
  'paid': 1,
  'ridden': 2,
  'risen': 2,
  'run': 1,
  'seen': 1,
  'sent': 1,
  'shaken': 2,
  'shown': 1,
  'shut': 1,
  'slept': 1,
  'spoken': 2,
  'spent': 1,
  'stood': 1,
  'stolen': 2,
  'struck': 1,
  'sworn': 1,
  'swum': 1,
  'taken': 2,
  'taught': 1,
  'thrown': 1,
  'told': 1,
  'torn': 1,
  'understood': 3,
  'woken': 2,
  'worn': 1,
  'written': 2,
};
